language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
node_js:
  - "node"
  - "9"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install -g polymer-bundler
script:
  - cd tracked-racer-app/
  - polymer install -v
  - polymer-bundler index.html --inline-scripts --inline-css --strip-comments > ../Esp8266/data/www/index.build.html && gzip ../Esp8266/data/www/index.build.html
deploy:
  skip_cleanup: true