language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  firefox: latest
  chrome: stable
node_js:
  - "node"
  - "stable"
stages:
- deploy
- ':deploy it to GH-PAGES'
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
script:
  - cd tracked-racer-app
  - npm install
  - sed -i 's|service-worker.js|tracked-racer/service-worker.js|g' index.html # expand path to match GH-PAGES root dir
  - sed -i 's|src="src=src|src="tracked-racer/src|g' index.html # expand path to match GH-PAGES root dir
  - polymer build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_PAGES_TOKEN
  keep-history: true
  local-dir: tracked-racer-app/build/public
  verbose: true
  on:
    branch: master