language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
node_js:
  - "node"
  - "9"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
script:
  - cd tracked-racer-app/
  - polymer install -v
  - cd ..
deploy: