language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  firefox: latest
  chrome: stable
node_js:
  - "node"
  - "stable"
stages:
- deploy
- ':deploy it to GH-PAGES'
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
script:
  - cd tracked-racer-app
  - npm install
  - polymer build
  - mv build/public build/tracked-racer
  - echo "<META http-equiv="refresh" content=\"0;URL=tracked-racer/\">" > index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_PAGES_TOKEN
  keep-history: true
  local-dir: tracked-racer-app/build
  verbose: true
  on:
    branch: master